### ISSUE TITLE
[Edit mode] Objects dropped into layout do not appear where dropped under some circumstances

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#384] opened 2015-12-08 05:40 UTC
In both old and new edit mode objects dragged into a layout can sometimes appear in a location other than where they were dropped.

In order to reproduce this behavior:

1. Edit a layout (in old or new edit mode)
2. Select an object (object A) from the tree, and drag-drop it somewhere over the layout. The object will appear in that position.
3. While still in edit mode, drag the same object (object A) into the same layout and drop it in a different position. Note the position where you dropped it. The object __should not appear__ in the layout, as it is already in the layout and multiple composition by the same object is not current allowed.
4. Staying in edit mode, drag and drop a different object (object B) into the layout in a third location, distinct from the first two. Object B will appear in the layout, in the position that Object A was dropped __the second time__ Object A will have moved to the position that Object B was just dropped.

![editmodebug](https://cloud.githubusercontent.com/assets/4215777/11648467/bcb8ff96-9d29-11e5-937c-85f5b6366a77.gif)

**Comment by larkin** [comment] 2015-12-08 19:26
https://github.com/nasa/openmctweb/issues/384 is a dupe of this issue.

**Comment by VWoeltjen** [comment] 2015-12-08 19:31
Marking critical - Editing is high priority currently and will receive scrutiny

**Comment by akhenry** [comment] 2015-12-08 23:56
This is resolved for old edit mode. Interestingly, it does not resolve #386. I will do some further investigation on that issue.

**Closed** 2015-12-08 23:57 UTC
Labels: bug, critical, NEM Beta

**Comment by akhenry** [comment] 2015-12-14 23:39
Verified the fix in Baxter Testathon 2 - 12/14/2015

**Comment by charlesh88** [comment] 2015-12-15 00:22
Testathon 20151214 confirmed working properly.
