### ISSUE TITLE
[Platform] Bump Angular Version to Latest (1.4.3)

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#57] opened 2015-07-30 15:39 UTC
We're currently using a legacy version of angular which is preventing us from using some very useful features (such as one-time bindings, which are useful for reducing watch counts).

I dropped in 1.4.3 and did not encounter any bugs with the application but I did not do a comprehensive check.

@VWoeltjen any thoughts about when we should schedule this and how much testing we should perform afterwards?

**Comment by VWoeltjen** [comment] 2015-07-30 17:39
I see two possibilities here:

- Make this change _after_ we reach version 1.0.0, to maximize the validity of our prior testing.
   - This also reduces our 1.0.0 API commitments, since Angular 1.4.3 has a generally larger API than our current version.
- Make this change ASAP, so that we have a lot of time to test before 1.0.0

I'm leaning toward the former since it seems lower-risk, but the latter is higher-benefit, so I could be talked into it.

In either case, I think we need to merge in our regression test suite first. That and our normal testathon cycle seem sufficient here.

Last time I'd checked, dropping in a new version of Angular was non-trivial because of changes to the requirements of controllers (I believe in the 1.3's you needed to use `this`-style constructors), so it is encouraging that 1.4.3 is not raising any immediate bugs.

**Comment by larkin** [comment] 2015-08-03 17:56
I would like to switch to 1.4.3 as soon as possible-- I think it should have a more stable API than what we currently have and has a number of performance enhancements that are valuable to us.  

It also reduces the impact of future angular version upgrades later on when we have committed to a stable version 1.0.0 of the platform.  

1.4.3 simplifies new developer onboarding (can point them at the latest angular docs) and allows us to use some new developer tools (chrome extensions, etc) that may improve development speed.

I agree that a regression test suite + testathon cycle are sufficient testing for a version upgrade.

**Comment by VWoeltjen** [comment] 2015-09-11 18:30
Resolved by #81

**Closed by VWoeltjen** 2015-09-11 18:30 UTC
