### ISSUE TITLE
Locator does not work when there is no context

### ISSUE THREAD

**Issue by slhale** [nasa/openmctweb#88] opened 2015-08-27 17:22 UTC
When a search result is selected, the LocatorController cannot find context. This means that when the create dialog is open, the tree to select the location to create that object is not loaded. Also, when attempting to edit a search result, the Library is not loaded. 

![screen shot 2015-08-27 at 10 21 04 am](https://cloud.githubusercontent.com/assets/2347849/9527626/199d3b94-4ca5-11e5-887f-18148fed86b8.png)
When this issue occurs, the tree appears to load infinitely, as above.

**Comment by VWoeltjen** [comment] 2015-08-27 17:25
@charlesh88 - does it even make sense to have Create available while searching? It seems a little funny to me.

I do think LocatorController should be robust enough to handle the case where context is unavailable, however (perhaps defaulting to use the root object explicitly?)

**Comment by charlesh88** [comment] 2015-08-27 17:38
Absolutely it makes sense to be able to Create while searching. To the user, these things are not connected. The fact that using search pwns context is a problem we need to address in general. I think you're suggesting that if there is no context, we default to My Items - if so, I agree.

**Comment by VWoeltjen** [comment] 2015-11-02 17:55
Can't reproduce, believe this was fixed by #119

**Closed by VWoeltjen** 2015-11-02 17:55 UTC

**Comment by RCarvalhoNASA** [comment] 2015-11-23 23:20
Testathon 20151123:  Verified this is working correctly
