### ISSUE TITLE
[Browser Support] Navigation tree appears initially collapsed in Firefox.

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#639] opened 2016-01-26 23:58 UTC
From #137

In Firefox, the tree appears collapsed by default. Behavior should be consistent with Chrome here.

![chrome](https://cloud.githubusercontent.com/assets/5769437/11728613/aad3d8b0-9f3f-11e5-9566-addd1591e095.JPG)
![firefox](https://cloud.githubusercontent.com/assets/5769437/11728614/aad34008-9f3f-11e5-9da5-43afdaa9fb78.JPG)
Attached are some screenshots to show the difference between the Chrome and Firefox 'home' views.

To reproduce:
1. Navigate to http://localhost:8080/#/browse/mine
2. Tree is partially collapsed, although some elements from the tree pane are visible, such as the create button.

@fbender You have expressed an interest in cross-browser support, so if you want to take a look at this let me know. Happy to provide any support you need

@charlesh88 do you have any initial thoughts on what might cause this? Could it be some mobile CSS related strangeness?

**Comment by fbender** [comment] 2016-02-12 08:33
I'll have a look at this next-next weekend. I assume it's related to some non-standard or otherwise inconsistent properties the layout calculation depends on.

@akhenry You'll get an e-mail from me in the next few days.

**Comment by larkin** [comment] 2016-02-17 00:54
This is caused by a webkit-only media query that causes certain css not to apply in firefox; it is not a race condition.  Determined via research after seeing solution for #683.

**Comment by charlesh88** [comment] 2016-02-17 01:01
Actually, we've figured out this is related to mobile media queries and webkit only statements. Will be pushing a fix shortly.

**Comment by charlesh88** [comment] 2016-02-18 20:02
Smoke testing:

File | Change | Verified by
---- | ---- | ----
_controls.scss | mini-tab-* surrounded by body.desktop | Ok

**Comment by charlesh88** [comment] 2016-02-22 21:19
Filed PR with #691, closing.

**Closed by charlesh88** 2016-02-22 21:19 UTC
Labels: bug

**Comment by charlesh88** [comment] 2016-03-04 00:06
Testathon 03032016
Confirmed functioning as desired for WARP in Linux / Chrome.
