### ISSUE TITLE
Page splitter doesn't set default size properly with high latency and clean cache.

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#53] opened 2015-07-27 16:28 UTC
I can reproduce this almost 90% of the time with the following settings:

* Chrome
* Developer tools open
* Cache disabled while developer tools open.
* Load https://openmctweb-demo.herokuapp.com/

When done properly, the page looks like so:

![screen shot 2015-07-27 at 9 23 57 am](https://cloud.githubusercontent.com/assets/226503/8911479/9a0f1418-3441-11e5-8cc6-42c6a336dc99.png)

I can sometimes reproduce this issue without the cache disabled, I believe it's a condition where the split view is using something (likely css) to set the default size of the tree view, and the css hasn't full applied yet, so the initial tree size is 0px, and the splitter sizes accordingly.

Dragging the splitter returns warp to normal functionality.

If this is a race with CSS loading, we may need to wait for css loading before initializing the application.

**Comment by VWoeltjen** [comment] 2015-07-29 16:20
A CSS race seems plausible.

This gets initialized at https://github.com/nasa/openmctweb/blob/ef77ca91e7f0c738633aac051960287f057208d4/platform/commonUI/general/src/directives/MCTSplitPane.js#L191-L193 which runs as soon as the directive is linked. A quick fix would be to put this on a timeout, I think

**Comment by VWoeltjen** [comment] 2015-07-29 16:29
A slightly more complete solution might be to add an intermediary class between [StyleSheetLoader](https://github.com/nasa/openmctweb/blob/ca4f37b25971efc91e08098741b09ed96ffe6f9f/platform/commonUI/general/src/StyleSheetLoader.js) and any scripts that need to depend on style sheets having been loaded (which would include MCTSplitter)

* StyleSheetLoader
  * Loads stylesheets
  * Listens for appropriate events to make sure these really are loaded (if this can be done reliably?)
  * Notifies intermediary
* Intermediary (as-of-yet-unnamed)
  * Waits to be notified that CSS is ready
  * Notifies any listeners
* MCTSplitPane
  * Asks to be notified by intermediary when CSS is ready
  * Intializes splitter position

This still feels a little bit tangled, but would be more reliable than a timeout

**Comment by larkin** [comment] 2015-08-03 19:08
As the "runs" extension category is intended for application initialization, does it make sense to have this extension category block initialization of the application until all extensions have completed?  Would result in more deterministic application loads and would remove coupling between MCTSplitPane and application load behavior.

Otherwise, we've got to couple (directly or indirectly) stylesheet loading to MCTSplitPane which seems like an unnecessary concern for MCTSplitPane to deal with.

**Comment by VWoeltjen** [comment] 2015-09-11 20:21
I don't think the `runs` approach would help here (and I believe it's the case that these get resolved by Angular before any routes get followed, in any case), since the problem isn't that the StyleSheetLoader hasn't completed, it's that the stylesheets themselves haven't finished loading.

I'm thinking the realistic thing we need to do is live with polling. This has an additional positive attribute, which is that it should be reasonably capable of detecting and adjusting for run-time changes in computed styles, which is probably an existing shortcoming of `mct-split-pane` that we just haven't run into yet.

**Closed** 2015-09-14 21:41 UTC

**Comment by larkin** [comment] 2015-09-18 20:50
Verified in 9/17/2015 testathon and in dev environment.
