### ISSUE TITLE
[Framework] Error loading application

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#662] opened 2016-02-09 22:28 UTC
When client loads there is an error appearing in the logs - "Cannot read property ‘split’ of null".

Not sure if it's due to a specific bundle enabled in the test environment, or as a consequence of minification, or something else entirely.

Does not cause any obvious ill-effects.

**Comment by VWoeltjen** [comment] 2016-02-09 22:46
Doubt this is a blocker, but we should understand root cause and consequences for purposes of triage. Is a source line number shown in the snack trace?

**Comment by akhenry** [comment] 2016-02-09 22:48
Are you hungry by any chance? :)

I'll do some initial triage and see if I can contextualize this problem a bit.

**Comment by akhenry** [comment] 2016-02-09 22:49
There is a line number, but it's in the minified code.

**Comment by VWoeltjen** [comment] 2016-02-09 22:56
Well that's a bummer.

Wonder why that is. Source maps are being generated as of #642, and it looks like `main.js.map` should get included in the build we're using. Is it present in the testathon build (in the `static` directory)?

**Comment by akhenry** [comment] 2016-02-09 22:56
From looking at line 6 of the minified code, the most likely culprit is 
```
return s=e.map(function(e){var t=e.split(":");return t.length>1?{id:e,space:t[0],key:t.slice(1).join(":")}:{id:e,space:l,key:e}})
```

**Comment by VWoeltjen** [comment] 2016-02-09 23:02
Who needs source maps anyway? Clearly that's from [PersistedModelProvider](https://github.com/nasa/openmctweb/blob/0a5097a945287d612e4c91a5490c2386f49160c1/platform/core/src/models/PersistedModelProvider.js#L114-L119)

I'm curious who the caller is, but I'm guessing that's from generic search indexing (I believe we've seen similar errors in the past)

**Comment by VWoeltjen** [comment] 2016-02-09 23:10
Think this may be a side effect of #356

**Comment by akhenry** [comment] 2016-02-09 23:17
Ok, so there are two source maps linked from the minified file -
```
//# sourceMappingURL=main.build.js.map
//# sourceMappingURL=main.js.map
```

There is 404 for `http://hulk:9080/static/main.build.js.map` and it appears to be absent from the build. Is this map essential?

**Comment by VWoeltjen** [comment] 2016-02-10 01:05
Adding blocker status until we understand root cause; should downgrade if this is benign

**Comment by VWoeltjen** [comment] 2016-02-10 01:09
@akhenry - w.r.t `main.build.js.map`, I'm not sure why that reference is being added to `main.js`. Our  task which minifies & generates source maps is [rather simple](https://github.com/nasa/openmctweb/blob/master/gulpfile.js#L75-L80); at no point are we saying "make a `main.build.js.map` file." Running locally, haven't had any issue with sourcemaps working as expected.

I'll self-assign and continue investigating

**Comment by VWoeltjen** [comment] 2016-02-10 17:35
Reproducible in open source on the master branch if you swap out ElasticSearch for the local storage adapter.

Relevant trace is:

```
Uncaught TypeError: Cannot read property 'split' of null(anonymous function) @ 
  PersistedModelProvider.js:115PersistedModelProvider.getModels @ 
  PersistedModelProvider.js:114(anonymous function) @ 
  ModelAggregator.js:91ModelAggregator.getModels @ 
  ModelAggregator.js:90CachingModelDecorator.getModels @ 
  CachingModelDecorator.js:107MissingModelDecorator.getModels @ 
  MissingModelDecorator.js:57GenericSearchProvider.beginIndexRequest @ VM2023 
  GenericSearchProvider.js:197GenericSearchProvider.keepIndexing @ VM2023 
  GenericSearchProvider.js:156(anonymous function) @ VM2023 GenericSearchProvider.js:211
```

Looks to be related to search indexing. Probably benign. Want to understand how those `null` values get into the search indexing process.

**Comment by VWoeltjen** [comment] 2016-02-10 17:54
This is actually a problem with persisted data. There's a "Migrated from Prototype" folder in this data set that contains an old "My Items " with a `null` value in its `composition`. Presumably there was a bug either in the migration script or in the prototype that allowed this `null` value in.

Impact is that some of the objects _after_ the `null` value don't get indexed for search, and the old "My Items" is not browseable. The missing objects are various test timelines that were made during user-testing of a prototype implementation of the timeline, so don't think anyone is missing these.

Want to fix with an update to the migrated data set (will file an issue for that in appropriate issue tracker); closing as there is no further action here.

**Closed by VWoeltjen** 2016-02-10 17:54 UTC
Labels: blocker, bug
