### ISSUE TITLE
[Testathon 12-07-15] Can't change telemetry point to plot view

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#381] opened 2015-12-07 23:24 UTC
Telemetry points have lost the capability to switch to plot view - they only display scrolling values.
Seen on 10.10.81.15:9080 on Linux workstation. Andrew also saw the problem.

**Comment by VWoeltjen** [comment] 2015-12-07 23:31
Is this true for telemetry points with numeric values? Plot view should be suppressed for image telemetry and telemetry with string values.

Hovering over a telemetry point in the tree will show some metadata; where Data Type is "number", plot should be available.

**Comment by larkin** [comment] 2015-12-08 00:21
@VWoeltjen it looks like everything is currently showing a data type of enum even when it should be a "number".  I suspect there may be issues with the dictionary but unsure.

**Comment by larkin** [comment] 2015-12-08 00:47
Confirmed with mark that the server is returning incorrect types for dictionary values.  I think we can close this as "not a client bug".

**Comment by VWoeltjen** [comment] 2015-12-08 01:07
Filed WTD-1599 in the current sprint for this, marked as a Critical to reflect state here. Closing this issue as the problem is external to Open MCT Web

**Closed by VWoeltjen** 2015-12-08 01:07 UTC
Labels: bug, critical

**Comment by RCarvalhoNASA** [comment] 2015-12-14 23:42
Testathon 20151214 this is working as expected.

**Comment by charlesh88** [comment] 2015-12-14 23:48
Testathon 20151214 confirmed working.
