### ISSUE TITLE
[TimeConductor] Navigation causes bounds updates to fire when bounds havent updated

### ISSUE THREAD

**Issue by larkin** [nasa/openmctweb#229] opened 2015-10-30 21:05 UTC
When the time conductor is enabled, navigating from one domain object to another via the tree causes the time conductor to fire a 'telemetry:display:bounds' event even though the time conductor's bounds have not changed.  It fires this event a total of two times, which causes components to generate a total of three telemetry requests when they are initially loaded.

Components with a large number of telemetry objects may experience noticable delay as large numbers of requests are generated.

**Comment by VWoeltjen** [comment] 2015-10-30 21:08
Does anything user-facing behave incorrectly as a result of this?

**Comment by larkin** [comment] 2015-10-30 21:11
@VWoeltjen apologies, posted before completed typing.  I noticed that there is a bit of a performance hit when loading pages with large numbers of telemetry object, and if batched minmax is not available, it causes multiple individual historical requests to be sent for the same set of data, which causes the http connection limit to be hit, and slows down loading of historical data.

**Comment by larkin** [comment] 2015-10-30 21:18
@VWoeltjen Even with a sine wave it is a performance hit.  Number of requests sent depends on what types of objects you are navigating from/to.

Navigating sine wave -> another sine wave: 3 telemetry requests are fired
navigating folder -> sine wave: 17 telemetry requests are fired.

**Comment by VWoeltjen** [comment] 2015-10-30 21:24
Huh! 17 is a funny number. Clicking back and forth causes those numbers to keep on growing (exponentially, it seems)

I'm betting this is listeners from previous controller instantiations not getting removed, although that doesn't explain exponential growth. If that is the cause (or part of it), that's a good reason to address #227 sooner than later

**Comment by larkin** [comment] 2015-10-30 21:25
@VWoeltjen folder -> sine wave is an interesting case; it just keeps getting worse.

It's thrashing the views considerably, as you can see by large numbers of gl contexts getting evicted from a single navigate action.

![screen shot 2015-10-30 at 2 24 07 pm](https://cloud.githubusercontent.com/assets/226503/10858401/fa6e7270-7f11-11e5-88e5-53bcbe020b9d.png)

**Comment by VWoeltjen** [comment] 2015-10-30 21:31
Looks like there's a mix of problems:

* Broadcasting is happening multiple times per navigation change, and the number of times is growing when switching over to a plot. This appears to be growing linearly.
* Number of telemetry requests issued as a result of broadcasting appears to be growing exponentially, implying listeners have not been correctly detached.

**Comment by larkin** [comment] 2015-10-30 21:37
* folder -> folder is consistently 2 bounds changed
* folder -> evr is 1 bounds changed
* evr list -> sine wave list is 1 bounds changed.
* plots seem to cause bounds changed events to fire more and more frequently.  (don't get how this works?)

Shouldn't throttle be preventing multiple bounds changed events from getting fired?

**Comment by VWoeltjen** [comment] 2015-10-30 21:48
It should be. I do see (at least on master) that domain switches are firing bounds changes immediately - the original domain selection is probably doubling up with the initial broadcast for bounds changes. That should be reasonably easy to fix.

Plots are a little different because they emit a `telemetry:view` event to trigger bounds to be broadcast. This had previously been necessary due to ordering, but as a byproduct of throttling broadcasts this should no longer be necessary.

Locally, made some changes to use `broadcastBounds` consistently and to remove the listener for the `telemetry:view` event. This causes broadcasts to occur a more sane number of times (still twice when going from plot -> folder, which is weird, but not my top concern).  With these changes, telemetry requests per folder->plot change progress linearly (4, 8, 12, 16, 20 requests...)

Broadcasting when view/navigation changes occurs does serve a purpose, insofar as plot needs to know its bounds for purposes of setting up the initial display area.

**Comment by VWoeltjen** [comment] 2015-10-30 21:51
Verified that old PlotController instances are hanging around as a consequence of listening to scope.

In the above configuration, every time I go from folder->plot I see:
* 2 telemetry requests per PlotController _before_ bounds are broadcast
* 2 telemetry requests per PlotController _after_ bounds are broadcast

**Comment by larkin** [comment] 2015-10-30 22:04
Sounds like #227 is the ideal fix here; destroying a scope removes all listeners and broadcasts the standard destroy event which any non-scope based listeners will listen on and use for clean up.

**Comment by VWoeltjen** [comment] 2015-10-30 22:09
Yep, trying out a quick-fix to #227 locally, it resolves the request-growth problem with no obvious regressions. Still getting four telemetry requests per folder->plot switch, but at least it's a stable four. Will focus on #227 first then circle back around here to figure out what's going on in plot.

Assigning this and #227 to Ballard, believe these issues are both important for this sprint

**Comment by larkin** [comment] 2015-10-30 22:25
:+1:

**Comment by VWoeltjen** [comment] 2015-11-02 23:52
Between changes on #230 and changes on branch open229, now see 4 total requests for my test case (a Telemetry Panel containing two sine waves) when I expect to see 2 (one for each sine wave) of switching from a folder to a panel

Pairs of requests are from initial plot instantiation, and plot reaction to initial broadcast of bounds, respectively. Can probably quickly fix this by throttling request initiation from plots

**Comment by larkin** [comment] 2015-11-03 17:36
@VWoeltjen Figured it's worth raising this here, but I don't think throttle is the right name for what the throttle service currently provides.  By definition, throttle controls the rate of function invocation, but the service we have delays invoking the function until it hasn't been called in a certain number of milliseconds-- it makes no guarantee as to the rate at which the function is invoked.

underscore/lodash calls this behavior "debounce"; , where debounce says "this won't call through until it has stopped being invoked for a certain amount of time".

What are your thoughts about pulling underscore/lodash into core?

**Comment by VWoeltjen** [comment] 2015-11-03 17:55
The JSDoc to `throttle` is poorly worded; it reflects the implementation, but ends up sounding more like debounce. (The ambiguity is in the phrase "only if no other invocations are pending"; this refers to the time at which the throttled function is called, but if read as referring to the time after the delay has passed this sounds like debounce.) It functions like `_.throttle` with the `{ leading: false }` option.

I'm all for using lodash from core; I'd find it very convenient. My preference would be to wrap it with things like `throttle` if there is a relevant subset of the API we want to expose from the platform (I'd like to move toward a place where we [expose no third-party APIs](https://github.com/nasa/openmctweb/blob/api-redesign/docs/src/design/proposals/APIRedesign.md#expose-no-third-party-apis).)

**Comment by akhenry** [comment] 2015-11-03 17:55
I would welcome underscore/lodash.

I've never particularly liked the term debounce though (outside of its original meaning which relates to processing keystrokes in keyboards).

**Comment by larkin** [comment] 2015-11-03 18:05
@VWoeltjen whoa, that's something I hadn't had time to process... "expose no third party APIs?"

I'd prefer we reuse and expose APIs that people are familiar with-- for one, it requires less documentation and maintenance on our part. two, it stops us from becoming a monolithic framework that is a career commitment to learn, and three, it drastically lowers the barrier to entry.  

Many people have used lodash/underscore.  Many people have used angular.  Many people have used requirejs.  Having to learn a new thing that is similar, but different than all three?  That's hard.

**Comment by akhenry** [comment] 2015-11-03 18:22
I tend to agree with @larkin. Arguably it complicates our own API and actually increases the learning curve if we end up having to replicate or wrap functionality already provided by popular third-party APIs that people are familiar with. 

I completely understand the motivation though. The world of web development is horribly fickle and frameworks that are ubiquitous now won't be in a few years. prototype.js anyone? Even the once mighty jquery has fallen out of favour. 

I think we should limit the third party APIs we expose to one or two, but I worry it might be counterproductive to completely hide them.

One option might be to provide lightweight facades to third party APIs ala Angular with its quasi-jQuery interface, but that feels a bit blergh.

**Comment by VWoeltjen** [comment] 2015-11-03 18:28
@larkin - I think that's the wrong conclusion to reach there. There's nothing stopping you from using lodash/require/etc. directly; we're compatible with other libraries and should try to make that compatibility simpler. In general, I don't think we should be re-exposing functionality that can be directly obtained from other more general-purpose libraries.

The idea that exposing third-party libraries reduces the learning curve has been directly contradicted by feedback we've gotten. We've regularly heard that "to use this I have to learn Open MCT Web, Angular, and Require." That's fine internally, but really it would be better if it was "to use this I have to learn Open MCT Web, and I can use it with the APIs I already know."

I think this is particularly important for a 1.0.0 release; if we're exposing third-party APIs at that point, we're committed to those dependencies in 2.0.0. Wrapping the things we want/need to expose narrows that commitment. 

Angular's a bit of a weird case because it provides quite a useful services library and templating syntax. My solution there would be (a) use that internally, or wrap it if we want to expose something similar, and (b) provide a non-platform Angular plug-in that does expose these things.

**Comment by larkin** [comment] 2015-11-03 18:54
Whether you're using require, browserify or plain script tags, the concept of a dependency loader is something you should be familiar with in every language.  People not interested in gaining a cursory understanding of these tools are really saying "I don't want to learn anything about web technologies".  Do we really want to cater to these people?

Lodash is a way of simplifying common functional patterns and reducing code.  Don't think we need to expose it, but don't think we need to recreate it.  If we use it in the platform, then it's there if people want it, but if they don't import it, they don't have to use it.

If you look at Angular tutorials, they look nothing like the code we write.  Angular is itself a monolith that tries to promote good programming practices, it handles many concerns that we have reimplemented separately.  So telling people it's angular, well, that isn't very helpful.  If it actually looked like angular, that would have more value.

When people say "I have to learn X, Y, and Z to use this" and then claim that they'd prefer to say "I only have to learn Z," well, if Z included all of X, Y, and Z, then they'd still have to learn it all.  I don't think it's because it's too many tools; I think the problem is it's not clear what the boundaries are between X, Y, and Z.[1]

As much as we call openmctweb a platform, I would better define it as a set of tools, common interfaces, and design patterns that is intended to be easily extensible and promote good development practices.



[1]: Haven't done web development before?  You're already in over your head: you've also got to learn A, B, and C too.

**Comment by VWoeltjen** [comment] 2015-11-03 19:02
This would be a good conversation to have in #69.

On the topic of this issue, throttling requests in plot isn't quite the quick-fix I'd hoped for - the throttle interval needs to be greater than the delay between PlotController initializing and the first bounds event being provided by the time conductor. Need to try a different approach here; maybe separate events?

**Comment by larkin** [comment] 2015-11-03 20:12
@VWoeltjen I'm okay saying "the plot doesn't have to handle this concern."  The larger issue here was the enormous growth of listeners that killed performance. And since this issue only occurs in certain configurations-- not all configurations-- it's quite complicated to handle well inside of the plot.  

A telemetry provider can implement request batching/memoizing ("i got the same request twice, i'll make one underlying request and use that to fulfill both requests") which solves the problem and also increases the performance when you have multiple views requesting the same data-- a use case I wouldn't rule out.  But that's a feature for another day.

The plot needs to have some sort of cancel handling to prevent race conditions-- if a new request is made before an old request resolves, the plot should disregard the response to the old request.  This might already be implemented, I'm not sure.

I'll copy/paste comments related to #69 to discussion thread in #69.

**Comment by VWoeltjen** [comment] 2015-11-03 23:24
> @VWoeltjen I'm okay saying "the plot doesn't have to handle this concern." The larger issue here was the enormous growth of listeners that killed performance. And since this issue only occurs in certain configurations-- not all configurations-- it's quite complicated to handle well inside of the plot. 

Growth of listeners is addressed by #230, so we're most of the way there in terms of performance.

> The plot needs to have some sort of cancel handling to prevent race conditions-- if a new request is made before an old request resolves, the plot should disregard the response to the old request. This might already be implemented, I'm not sure.

I think you're right that there is a race condition in here. The plot unsubscribes from its `TelemetryHandle`, but this doesn't prevent pending request callbacks from being invoked. I feel it would make sense to do so; I'll go ahead any make this change in the context of this issue.

**Closed** 2015-11-09 19:45 UTC
