### ISSUE TITLE
Unsaved Changes dialog not working correctly in Timelines

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmctweb#660] opened 2016-02-09 22:12 UTC
Testathon 20160209

When a user is editing in NEM and clicks the "X" to cancel editing in the upper right of the interface, the unsaved changes dialog is displayed. If the user clicks "Cancel" in that dialog, they should be taken back to edit mode. Instead, edit mode is actually exited *before* the dialog is displayed, and the system is put into a weird half edit-mode, half browse-mode situation: Save/Cancel buttons are not displayed, the Create button *is* displayed, but clicking anywhere in the tree results in the unsaved changes dialog being displayed as if the user was still editing.

Ideally, clicking the cancel edit "X" button should have the same result as if the user tried to navigate elsewhere while editing: the unsaved changes dialog is displayed and clicking Cancel in that dialog should keep the user in edit mode.

**Comment by akhenry** [comment] 2016-02-09 23:27
This is addressed in https://github.com/nasa/openmctweb/issues/627 Since it's critical, I could try and address it separately before Wednesday if need be.

**Comment by akhenry** [comment] 2016-02-09 23:38
> Ideally, clicking the cancel edit "X" button should have the same result as if the user tried to navigate elsewhere while editing: the unsaved changes dialog is displayed and clicking Cancel in that dialog should keep the user in edit mode.

This has been broken out into a separate issue - https://github.com/nasa/openmctweb/issues/664

**Comment by akhenry** [comment] 2016-02-10 00:10
Have confirmed after recreating successfully in WARP and master that it is indeed already fixed in #627

**Comment by VWoeltjen** [comment] 2016-02-10 01:03
Is it possible to separate out the changes which address (or partially address) this from #651? Would like to address this in isolation before introducing new functionality (plot options)

**Comment by akhenry** [comment] 2016-02-10 01:26
The bits of #627 that address this do not directly depend on #651. Extricating just those bits from the branch will inevitably involve some duplication of effort though, as they'll have to be shoehorned into the browse controller and markup in master, changes which will then be discarded when #627 is merged. It could totally be done in the timeframe though.

**Comment by VWoeltjen** [comment] 2016-02-10 01:49
Got it. Don't want to waste too much effort, but also see that #651 is still undergoing changes for review and don't want to rush that.

Given that, I'd propose to base the decision on a ballpark time estimate for cherry-picking (in  the git sense and/or manual copy+paste sense). 

* If we're talking hours or days (not sure how deeply those changes are embedded in other browse mode changes), then I think we should focus on getting #651 and #627 merged; this is consistent with the spirit of code freeze (it's the most efficient solution to a blocker.) 
* If it's shorter than that, then the duplicated effort is pretty minimal, and I think the procedural risk mitigation would make it worthwhile to separate out just the changes which address this issue.

@charlesh88 - what are your thoughts on these approaches?

**Comment by akhenry** [comment] 2016-02-10 03:59
Have created a PR #665 for a fix for this. Turns out it's fairly straightforward to fix in master. The code in error was introduced as part of NEM, and I have applied a fix to this code. Might be possible to refactor out the NEM code here as part of #627

**Closed** 2016-02-11 01:09 UTC
Labels: blocker, bug, critical

**Comment by RCarvalhoNASA** [comment] 2016-02-11 22:41
Testathon 20160211 I went in to edit a timeline, added an activity, then started to attempt to test this (close without save by clicking the X).  It simply let me do so without any kind of warning dialog that I would lose my changes.

**Comment by akhenry** [comment] 2016-02-11 22:47
@RCarvalhoNASA Unfortunately a known issue for this sprint, there is a ticket to address this - #664

**Comment by akhenry** [comment] 2016-02-11 23:01
Testathon 20160211

Verified as fixed.
