### ISSUE TITLE
[Search] No context menu for search results

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmctweb#120] opened 2015-09-17 22:32 UTC
Enter a search query that brings up more than zero results. 

Right click on a search result. Observe: No context menu appears.

Regular click on the search result to navigate to it, then click on the context menu arrow in the title area. Observe: No context menu appears.

Observed during testathon, 9/17/2015

**Comment by VWoeltjen** [comment] 2015-09-17 23:00
This only occurs when there is no `context` capability for a domain object (which can happen when there is no `location` specified for the domain object.)

Exception is in [AbstractComposeAction](https://github.com/nasa/openmctweb/blob/6aaa887e658a91166270de0ab066168d2575f6ed/platform/entanglement/src/actions/AbstractComposeAction.js#L82)

**Comment by VWoeltjen** [comment] 2015-11-09 23:35
Can't reproduce in nominal cases as of 51968954a98815b87e1af72ff68d0fcaf3aeb905; domain object appears correctly navigated-to. Believe this was resolved by #119.

Still see this for "missing" objects, since they have no location. Would like to add a try-catch around Action instantiation to improve overall robustness.

**Comment by larkin** [comment] 2015-11-10 00:34
I have noticed that while there are background operations executing (typically large index operations), context menus do not reliably open. It appears that when background operations have completed, context menus start working again.

Happens to me frequently with large datasets. I actually think the issue may be the xhr request necessary to load the template is queued behind other requests. So may be completely unrelated?

Pete

On Nov 9, 2015, at 3:35 PM, Victor Woeltjen <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't reproduce in nominal cases as of 5196895<https://github.com/nasa/openmctweb/commit/51968954a98815b87e1af72ff68d0fcaf3aeb905>; domain object appears correctly navigated-to. Believe this was resolved by #119<https://github.com/nasa/openmctweb/pull/119>.

Still see this for "missing" objects, since they have no location. Would like to add a try-catch around Action instantiation to improve overall robustness.

**Closed** 2015-11-20 21:08 UTC
