### ISSUE TITLE
[Plot] Clicking range selector in some plots shows white square

### ISSUE THREAD

**Issue by akhenry** [nasa/openmctweb#342] opened 2015-11-24 01:14 UTC
1. Select a plot (eg. My Items > RP 15 Layouts > Power Layout > Batt SOC
1. Click on the Range label to switch range.
1. A white square appears briefly, then disappears, along with the range selector.

This was seen in Chrome in RH Linux on the RTScience machine

**Comment by VWoeltjen** [comment] 2015-11-24 19:34
Want to determine if there is any loss of data or incorrect display of data associated with this. If not, can remove Blocker label

**Comment by akhenry** [comment] 2015-11-24 22:36
Appears to be either OS or chrome version specific. Environments tested:
* OSX / chrome 46 - shows range axes options
* Ubuntu / chrome 46 - shows range axes options
* RH / chrome 34 (on rtscience machine)  - does not show options, instead shows white square

**Comment by akhenry** [comment] 2015-11-24 23:31
* RH 6.6 / Firefox 31.6.0 (rtscience) - Shows options, but they disappear very quickly.

**Comment by VWoeltjen** [comment] 2015-11-24 23:33
Is there any change in data displayed after this occurs? It's a bug that this is showing up at all in this case, since there's only one range available to choose from. But if data continues to display as expected after this occurs, I think we can un-categorize this as a blocker.

**Comment by akhenry** [comment] 2015-11-24 23:35
Data is still visible. Prevents selection of other domain and range values though. Not sure if this would constitute a blocker in RP.

**Comment by akhenry** [comment] 2015-11-24 23:36
To clarify, the data displayed is unaffected when clicking on the select box.

**Comment by VWoeltjen** [comment] 2015-11-24 23:39
Each telemetry point in RP only has one range available, so no loss of functionality as a byproduct of this. I would not consider this a blocker.

**Comment by akhenry** [comment] 2015-11-24 23:42
OK great. How about Vista?

**Comment by VWoeltjen** [comment] 2015-11-25 00:01
Ah, good point, this could be problematic in VISTA. @larkin - would you consider this a blocker for that application?

I'm curious if this is still the behavior when multiple range options are available. Are you able to reproduce this behavior with a Sine Wave Generator? (I'd test this by cloning the open source repo on the machine where you observe this, then running app.js)

**Comment by larkin** [comment] 2015-11-25 00:03
This isn't used in VISTA.  And as far as I can tell, it's never been a completely functional feature outside of the SinewaveGenerator, so I'd be happy back-burnering it.  

Think we have more pressing features to spend time on.

**Comment by akhenry** [comment] 2015-11-25 00:04
Yep, it is still an issue when multiple range options are available.

**Comment by charlesh88** [comment] 2016-01-08 02:43
@akhenry @VWoeltjen 
Just took a look at this on the RTSCIENCE workstation. Telem elems specifically were: 
* RP15 Layouts > Power Layout
 * BMS_VOLTAGE
 * Batt SOCC
* AMCook
 * AmandaLayout

There are two issues here:

#1 The disappearing act
#1 The white box

On #1, particular noted that that element uses ng-show = representation.showControls (plot.html line 63) which I think is the heart of this problem. That very same custom select is used in the Create Timer dialog, and works just fine there. I suggest converting from using .showControls to an HTML CSS hover over the Y axis area to control hide and show, and see if that solves the problem.

On #2, I do think that's CSS related: the text in the real select (the white box) might be picking up a white foreground color in that context. I'll look into this.

One note: the range options element in all cases had a single <option> element: "Value". Line 64 in plot.html has `ng-if="axes[1].options.length > 0">`. This UI element shouldn't be displayed if there's only a single value, so I think the length eval should be > 1.

**Comment by VWoeltjen** [comment] 2016-01-08 17:41
> On #1, particular noted that that element uses ng-show = representation.showControls (plot.html line 63) which I think is the heart of this problem. That very same custom select is used in the Create Timer dialog, and works just fine there. I suggest converting from using .showControls to an HTML CSS hover over the Y axis area to control hide and show, and see if that solves the problem.

Agree, think that removing that `ng-show` entirely and creating the desired effect with CSS is a good solution here.

> On #2, I do think that's CSS related: the text in the real select (the white box) might be picking up a white foreground color in that context. I'll look into this.

Interesting! So the real select is providing a native background (white) but picking up foreground color from CSS (also white)? That seems quite plausible, and would explain why the problem is platform-specific

> One note: the range options element in all cases had a single element: "Value". Line 64 in plot.html has ng-if="axes[1].options.length > 0">. This UI element shouldn't be displayed if there's only a single value, so I think the length eval should be > 1.

Good catch, that's probably the reason we see this for telemetry points we shouldn't.

**Comment by charlesh88** [comment] 2016-01-12 21:23
Select `<option>` elements don't currently allow styling via CSS, so not sure what's causing the white boxes. This might be an answer: http://askubuntu.com/questions/641098/blank-select-options-on-chrome-chromium-ubuntu-14-04

If this is true, we may need to get rid of selects entirely and use our own menus instead.

**Comment by larkin** [comment] 2016-01-12 21:40
Have to remember that "hover" isn't an interaction we can support on mobile.

I would question having the select menu being visible on hover, and additionally, being visible in this location.  What if it were a property of the plot which would be editable in the inspector pane?

I think to myself, "focus on getting all displays to the same standard of configurability and use same modality for configuration across all views, before adding view specific gestures."

**Comment by charlesh88** [comment] 2016-01-12 23:59
Work pushed to open342. Pull request filed with #476.
* Now using CSS hover on pertinent plot areas instead of .showControls;
* Refining of select styling, tweaks for Firefox Linux;
* Tweaks to local-control positioning in plots;
* Changed *-options controls to use length > 1 instead of > 0;

**Comment by charlesh88** [comment] 2016-02-22 21:21
#476 was merged into open, this should make it in the next testathon.

**Comment by charlesh88** [comment] 2016-03-01 16:47
@VWoeltjen If you're pulling together instructions for the testathon, could you include this issue? Thanks.

**Comment by charlesh88** [comment] 2016-03-15 18:48
Testathon 031516
Verified fixed on Linux Chrome.
Range selector no longer appears when number of range options is less than 2, this may have been the root of the issue. Cannot duplicate problem at this point.

**Closed by charlesh88** 2016-03-15 18:48 UTC
Labels: bug, needs investigation
