### ISSUE TITLE
Selecting a single telemetry point in search results ... no updates

### ISSUE THREAD

**Issue by Costigan** [nasa/openmctweb#334] opened 2015-11-23 23:47 UTC
I typed 'rmm_state' in the search box.
I then selected the matching point RMM_STATE_DAT.RMM_MODE and switched the view to scrolling.  I haven't seen any updates for a long while.

If I select the matching result 'RMM_STATE_DAT', i.e., the packet, I do see an update eventually, but not quickly.  I'm not sure if that means that the server is loaded s.t. the switch is delayed or the cvt updates aren't working.

**Comment by VWoeltjen** [comment] 2015-11-24 19:23
Marking as a blocker for now - may want to reduce severity on investigation if we find that this is not as severe as it sounds.

**Comment by VWoeltjen** [comment] 2015-11-24 19:25
Assigning to self for now; if I run into trouble reproducing, will reassign over to @akhenry who has access to test environment where this is observed.

**Comment by VWoeltjen** [comment] 2015-11-24 21:46
Able to reproduce. In this case, I see two variants of this telemetry point in the Search results. If I run without a database, I only see one version of the object. This prompted me to compare identifiers; the two different versions of the object have different casing (one is upper case, one is lower case.)

![open334-ids](https://cloud.githubusercontent.com/assets/1685764/11381049/96249794-92ae-11e5-9330-37980a08b72c.png)

What has happened is that an existing display somewhere in the database contains RMM_MODE  (referred to by its id), but uses the lowercase variant. At some point since the display was created, the dictionary definition (or possibly the server) was changed such that the identifier was reported as uppercase. With the exception of display-time concerns, all of the client code for dealing with these identifiers is case-sensitive, so the lowercase variant gets treated as an unknown telemetry point (the same as a telemetry point that has been removed from the dictionary.)

In terms of severity, I'd advocate removing the blocker label for this and handling it in the next sprint, under the rationale:

* Root cause of missing data is well-understood; no reason to believe navigating to an object in the dictionary would cause this.
* There is some visual indication (a change in icon with a question mark) that this is not a valid object. 

In terms of addressing this, would like to do this on two fronts:

* Improve clarity of visual indicator for unknown telemetry points.
  * Consider disabling telemetry-related views for unknown telemetry points.
* Handle point identifiers case-insensitively; removing an identifier should break existing displays in this manner, but changing the casing should not.

**Comment by VWoeltjen** [comment] 2015-12-14 17:17
Resolved by https://trunk.arc.nasa.gov/jira/browse/WTD-1590

**Closed by VWoeltjen** 2015-12-14 17:17 UTC
Labels: bug

**Comment by charlesh88** [comment] 2015-12-14 23:52
Testathon 20151214 confirmed working via RP15 Layouts > Payload Power Layout > DGV001W - Drill Power telemetry element.
